---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: licenta
  name: licenta
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: licenta
  template:
    metadata:
      labels:
        app: licenta
    spec:
      containers:
        - image: server1_image
          imagePullPolicy: Never
          name: licenta
          command:
            ["uvicorn", "wsgi:app", "--port", "5000", "--host", "0.0.0.0"]
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "300m"

#Workers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: licenta-worker
  name: licenta-worker
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: licenta-worker
  template:
    metadata:
      labels:
        app: licenta-worker
    spec:
      containers:
        - image: server1_image
          imagePullPolicy: Never
          name: licenta-worker
          command:
            ["celery", "--app=tasks", "worker", "--loglevel=info", "-c", "5"]
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          env:
            - name: BACKEND
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: BACKEND
            - name: BROKER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: BROKER

# Flower UI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-ingestion-flower
  name: worker-ingestion-flower
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-ingestion-flower
  template:
    metadata:
      labels:
        app: worker-ingestion-flower
    spec:
      containers:
        - image: server1_image
          imagePullPolicy: Never
          name: worker-ingestion-flower
          command:
            [
              "celery",
              "--app=tasks",
              "flower",
              "--port=5001",
              "--broker=amqp://default:default@rabbitmq:5672/",
              "--address=0.0.0.0",
              "--purge_offline_workers=120",
            ]
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          ports:
            - containerPort: 5001
---

