# Service frontend
apiVersion: v1
kind: Service
metadata:
  labels:
    app: licenta
  name: licenta
  namespace: default
spec:
  selector:
    app: licenta
  ports:
    - name: metrics
      port: 80
      targetPort: 5000

# Service Monitor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: licenta
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: licenta
  endpoints:
    - port: metrics
      path: /metrics
      interval: 2s
