apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{.Values.rabbitmq.target}}-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: {{.Values.rabbitmq.target}}
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 5
  maxReplicaCount: 20
  triggers:
    - type: rabbitmq
      metadata:
        host: {{.Values.rabbitmq.address}}
        protocol: auto
        queueName: {{.Values.rabbitmq.queueName}}
        mode: QueueLength
        value: {{.Values.rabbitmq.queueLength}}